# Generated by Django 4.2.16 on 2024-10-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appIngenieriaWebProyectoColaborativo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='pelicula',
            new_name='peliculas',
        ),
    ]
