# Generated by Django 4.2.16 on 2024-11-12 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appIngenieriaWebProyectoColaborativo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='antiguedad',
        ),
        migrations.AddField(
            model_name='personaje',
            name='estatura',
            field=models.IntegerField(default=1.8),
        ),
        migrations.AlterField(
            model_name='personaje',
            name='fecha_muerte',
            field=models.DateField(null=True),
        ),
    ]
